import Head from "next/head";
import AddPost from "../components/AddPost";
import { motion } from "framer-motion";
import Posts from "../components/Posts";
import nookies from "nookies";
import { firebaseAdmin } from "../firebase/firebase-admin";
import { collection, getDocs, orderBy, query } from "firebase/firestore";
import { db } from "../firebase/firebase";

export default function Home({ postProps }) {
	//landing animation
	const landingVariants = {
		initial: {
			y: 300,
			opacity: 0,
		},
		animate: {
			y: 0,
			opacity: 100,
		},
	};

	return (
		<div>
			<Head>
				<title>Fakeagram</title>
				<meta
					name="Instagram clone "
					content="Generated by create next app"
				/>
			</Head>

			<motion.main
				variants={landingVariants}
				initial="initial"
				animate="animate"
				transition={{ delay: 0.6 }}
				className="pb-28 mt-28"
			>
				<AddPost />
				<Posts postProps={postProps} />
			</motion.main>
		</div>
	);
}

export async function getServerSideProps(context) {
	try {
		const cookies = nookies.get(context);
		const token = await firebaseAdmin.auth().verifyIdToken(cookies.token);
		const { uid } = token;
		let post = [];
		const q = query(collection(db, "posts"));
		const querySnapshot = await getDocs(q);
		querySnapshot.forEach((doc) => {
			post.push({ ...doc.data(), id: doc.id });
		});
		if (uid) {
			return {
				props: {
					postProps: post || [],
				},
			};
		}
	} catch (error) {}
	return {
		redirect: {
			permanent: false,
			destination: "/Signin",
		},
	};
}
